### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by gesavoigt** [labsyspharm/palom#14]
We want to create an nf-core module based on palom. Currently, no information on the licence of this repository is available (though others e.g., Ashlar, have an MIT licence). It would be very helpful if you could decide on a licence so that the software can be more widely used.
Thanks in advance!

**Comment by Yu-AnChen** [comment]
Thank! Closing with 33f5a054d66f7aaf0490d33ea24b0e4c1e9ada62
