### ISSUE TITLE
Add imagecodecs to the prerequisites

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/palom#6]
`palom.pyramid.write_pyramid()` throws the following error by default:

`ValueError: <COMPRESSION.JPEG: 7> requires the 'imagecodecs' package`

Appears to be resolved with `pip install imagecodecs`.

**Comment by Yu-AnChen** [comment]
I think it was raising the error when reading the imaging file - palom currently only writes uncompressed tiff. That being said, I'm happy to add `imagecodecs` in the next release 🙂
